services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL_ARG: ${API_URL}
    env_file: .env
    environment:
      PORT: 8081
    volumes:
      - .:/app/
    ports:
      - "8081:8081"
    command:
      - "java"
      - "-jar"
      - "-Dspring.profiles.active=dev"
      - "/app/target/studio1way-0.0.1-SNAPSHOT.jar"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        API_URL_ARG: ${API_URL}
    env_file: .env
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    command: ["npm", "run", "start-dev"]
    depends_on:
      - web