services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    command:
      - "java"
      - "-jar"
      - "-Dspring.profiles.active=dev"
      - "/app/target/studio1way-0.0.1-SNAPSHOT.jar"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
    depends_on:
      - web