version: 2.1

jobs:
  build-web-prod:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build --target=prod -t "studio1way/web:test_${CIRCLE_SHA1:0}" .
      - run:
          name: Save image as tar
          command: |
            mkdir -p images && docker image save -o "images/studio1way_web_prod_${CIRCLE_SHA1}" "studio1way/web:prod_${CIRCLE_SHA1:0}"
      - persist_to_workspace:
          root: .
          paths:
            - images

  build-web-test:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build --target=dev -t "studio1way/web:test_${CIRCLE_SHA1:0}" .
      - run:
          name: Save image as tar
          command: |
            mkdir -p images && docker image save -o "images/studio1way_web_test_${CIRCLE_SHA1}" "studio1way/web:test_${CIRCLE_SHA1:0}"
      - persist_to_workspace:
          root: .
          paths:
            - images

  build-frontend:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t "studio1way/frontend:${CIRCLE_SHA1:0}" -f ./frontend/Dockerfile .
      - run:
          name: Save image as tar
          command: |
            mkdir -p images && docker image save -o "images/studio1way_frontend_${CIRCLE_SHA1}" "studio1way/frontend:${CIRCLE_SHA1:0}"
      - persist_to_workspace:
          root: .
          paths:
            - images

  test-web:
    docker:
      - image: cimg/base:2023.08
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load image
          command: |
            docker image load < "images/studio1way_web_test_${CIRCLE_SHA1}"
      - run:
          name: Test
          command: |
            docker run "studio1way/web:test_${CIRCLE_SHA1}" ./mvnw test

  test-frontend:
    docker:
      - image: cimg/base:2023.08
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load image
          command: |
            docker image load < "images/studio1way_frontend_${CIRCLE_SHA1}"
      - run:
          name: Test
          command: |
            docker run "studio1way/frontend:${CIRCLE_SHA1}" npm run test-ci

  deploy:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load image
          command: |
            docker image load < "images/studio1way_web_prod_${CIRCLE_SHA1}"
      - run:
          name: Retag for deployment
          command: |
            docker tag "studio1way/web:prod_${CIRCLE_SHA1}" "registry.heroku.com/${HEROKU_APP_NAME}/web"
      - run:
          name: Deploy
          command: bin/deploy-ci


workflows:
  run-jobs:
    jobs:
      - build-web
      - build-frontend
      - test-web:
          requires:
            - build-web
      - test-frontend:
          requires:
            - build-frontend
      - deploy:
          requires:
            - test-web
            - test-frontend
          filters:
            branches:
              only:
                - main